apiVersion: apps/v1
kind: Deployment
metadata:
  name: __NAME__
  labels:
    app: __NAME__
spec:
  replicas: 5
  selector:
    matchLabels: 
      app: __NAME__
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 50%
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: __NAME__
    spec:
      containers:
      - name: __NAME__
        image: __IMAGE__
        ports:
          - name: http
            containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/v1/trainees
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/v1/trainees
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
---
kind: Service
apiVersion: v1metadata:
  name: __NAME__
spec:
  selector: __NAME__
    app:
  ports:
    - port: 5000
    # Default port for image


