apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: haproxy
  labels:
    app: haproxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: polianskiyvasyl/haproxyapi-5
        env:
        - name: MARIA_SS_0_ADDR
          value: 10.233.71.34
        - name: MARIA_SS_1_ADDR
          value: 10.233.74.190
        - name: MARIA_SS_2_ADDR
          value: 10.233.75.36
        ports:
        - name: mysqlport
          containerPort: 3306
        - name: webuiport
          containerPort: 8080
