apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 50%
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: polianskiyvasyl/devops335-api:user7-dev-0c7a08d3-a9bb-40f8-a99d-bc8a87d460a2
        ports:
          - name: http
            containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/v1/trainees
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/v1/trainees
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5

kind: Service
apiVersion: v1
metadata:
  name: api
spec:
  ports:
  - name: api
    port: 3000
    nodePort: 30005
    protocol: TCP
  selector:
     app: api
  type: NodePort
status:
  loadBalancer: {}
---
